version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.dockerfile
    ports:
      - "8080:8080"
    networks:
      - crm-network

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.dockerfile
    ports:
      - "3000:3000"
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge
